### ISSUE TITLE
Go-finance blog post

### ISSUE THREAD

**Issue by asad-awadia** [alpeb/go-finance#5]
Hey @alpeb ,

I really liked your library and wrote a post about it here: https://blog.aawadia.dev/2020/11/30/finance-concepts-go-finance/

Could I get a link in the readme for it? It can serve as documentation examples for the library

Thanks!

**Comment by alpeb** [comment]
Wow that's pretty cool @asad-awadia , thanks! :smiley:  I've just updated the README :+1:
