### ISSUE TITLE
Test PriceDiscount() failed

### ISSUE THREAD

**Issue by mrtomyum** [alpeb/go-finance#6]
Running tool: /usr/local/go/bin/go test -timeout 30s -coverprofile=/var/folders/9r/2trm49kn7vxc6rx_2659xkx80000gn/T/vscode-goGuEEhk/go-code-cover github.com/alpeb/go-finance/fin

--- FAIL: TestPriceDiscount (0.00s)
    /Users/tom/go/src/github.com/alpeb/go-finance/fin/bonds_test.go:130: PriceDiscount(1203120000, 1204329600, 0.052500, 100.000000, 0) = 99.781250
    /Users/tom/go/src/github.com/alpeb/go-finance/fin/bonds_test.go:130: PriceDiscount(1203120000, 1204329600, 0.052500, 100.000000, 4) = 99.781250
FAIL
coverage: 93.3% of statements
FAIL	github.com/alpeb/go-finance/fin	0.004s
FAIL

**Comment by alpeb** [comment]
Thanks for the report @mrtomyum . I'm currently on the road, so I'll give this a check next week :truck: :+1:

**Comment by alpeb** [comment]
I couldn't reproduce this problem. The project certainly doesn't have 100% test coverage, but still the tests should pass...
